const evaluationData = {
  metadata: { dataset: "9-8GT-right-quarter", clips: 9, goals: 5, non_goals: 4, models_tested: 11, families: 3 },
  modelSummaries: [
    { model: "smolvlm2-2.2b", config: "224px, 3 frames, orig prompt", size: "2.2B", tp: 5, fn: 0, fp: 4, tn: 0, errors: 0, f1: 0.7143, accuracy: 0.5556, precision: 0.5556, recall: 1.0, team_accuracy: 0.0, avg_latency: 0.0, behavior: "always_goal" },
    { model: "smolvlm2-2.2b", config: "224px, 3 frames, new prompt", size: "2.2B", tp: 5, fn: 0, fp: 4, tn: 0, errors: 0, f1: 0.7143, accuracy: 0.5556, precision: 0.5556, recall: 1.0, team_accuracy: 0.6, avg_latency: 1.14, behavior: "always_goal" },
    { model: "smolvlm2-2.2b", config: "56px, 23 frames, 2fps", size: "2.2B", tp: 5, fn: 0, fp: 4, tn: 0, errors: 0, f1: 0.7143, accuracy: 0.5556, precision: 0.5556, recall: 1.0, team_accuracy: 0.6, avg_latency: 0.96, behavior: "always_goal" },
    { model: "moondream:1.8b", config: "224px, 1 frame, descriptive prompt", size: "1.8B", tp: 3, fn: 2, fp: 4, tn: 0, errors: 0, f1: 0.5, accuracy: 0.3333, precision: 0.4286, recall: 0.6, team_accuracy: 0.6667, avg_latency: 2.81, behavior: "mixed" },
    { model: "qwen3-vl:8b", config: "224px, 3 frames", size: "8B", tp: 1, fn: 4, fp: 0, tn: 4, errors: 0, f1: 0.3333, accuracy: 0.5556, precision: 1.0, recall: 0.2, team_accuracy: 0.0, avg_latency: 12.34, behavior: "conservative" },
    { model: "moondream:1.8b", config: "224px, 1 frame, direct prompt", size: "1.8B", tp: 1, fn: 4, fp: 0, tn: 4, errors: 0, f1: 0.3333, accuracy: 0.5556, precision: 1.0, recall: 0.2, team_accuracy: 1.0, avg_latency: 1.34, behavior: "conservative" },
    { model: "qwen3-vl:8b", config: "56px, 23 frames, 2fps", size: "8B", tp: 0, fn: 5, fp: 0, tn: 4, errors: 0, f1: 0.0, accuracy: 0.4444, precision: 0, recall: 0.0, team_accuracy: 0.0, avg_latency: 30.87, behavior: "always_not_goal" },
    { model: "qwen3-vl:2b", config: "56px, 23 frames, 2fps", size: "2B", tp: 0, fn: 5, fp: 0, tn: 4, errors: 0, f1: 0.0, accuracy: 0.4444, precision: 0, recall: 0.0, team_accuracy: 0.0, avg_latency: 8.1, behavior: "always_not_goal" },
    { model: "qwen3-vl:2b", config: "56px, 1 frame, num_predict=500", size: "2B", tp: 0, fn: 5, fp: 0, tn: 4, errors: 0, f1: 0.0, accuracy: 0.4444, precision: 0, recall: 0.0, team_accuracy: 0.0, avg_latency: 6.08, behavior: "always_not_goal" },
    { model: "qwen3-vl:8b", config: "56px, 1 frame, num_predict=500", size: "8B", tp: 0, fn: 5, fp: 0, tn: 4, errors: 0, f1: 0.0, accuracy: 0.4444, precision: 0, recall: 0.0, team_accuracy: 0.0, avg_latency: 12.82, behavior: "always_not_goal" },
    { model: "qwen3-vl:4b", config: "112px, 1 frame, num_predict=500", size: "4B", tp: 0, fn: 5, fp: 0, tn: 4, errors: 0, f1: 0.0, accuracy: 0.4444, precision: 0, recall: 0.0, team_accuracy: 0.0, avg_latency: 20.41, behavior: "always_not_goal" },
  ],
  clips: [
    { name: "goal_01_283s_Dark-sportswear", truth: "goal", team: "Dark sportswear", type: "goal" },
    { name: "goal_05_606s_Dark-suits", truth: "goal", team: "Dark suits", type: "goal" },
    { name: "goal_09_947s_Dark-suits", truth: "goal", team: "Dark suits", type: "goal" },
    { name: "goal_13_1646s_Dark-suits", truth: "goal", team: "Dark suits", type: "goal" },
    { name: "goal_17_2129s_Dark-sportswear", truth: "goal", team: "Dark sportswear", type: "goal" },
    { name: "nongoal_04_189s", truth: "not_goal", team: null, type: "not_goal" },
    { name: "nongoal_08_1198s", truth: "not_goal", team: null, type: "not_goal" },
    { name: "nongoal_12_1557s", truth: "not_goal", team: null, type: "not_goal" },
    { name: "nongoal_16_1986s", truth: "not_goal", team: null, type: "not_goal" },
  ],
  perClipResults: {
    "goal_01_283s_Dark-sportswear": {
      "smolvlm2-2.2b (224px, 3 frames, orig prompt)": { pred: "goal", team: "Team A", goal_correct: true, team_correct: false, latency: 0, raw: "{\"goal\": true, \"team\": \"Team A\"}..." },
      "smolvlm2-2.2b (224px, 3 frames, new prompt)": { pred: "goal", team: "Dark suits", goal_correct: true, team_correct: false, latency: 2.9, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (224px, 3 frames)": { pred: "goal", team: "Dark suits", goal_correct: true, team_correct: false, latency: 49.8, raw: "{\"goal\": true, \"team\": \"Dark suits\"}" },
      "smolvlm2-2.2b (56px, 23 frames, 2fps)": { pred: "goal", team: "Dark suits", goal_correct: true, team_correct: false, latency: 3.0, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 35.6, raw: "" },
      "qwen3-vl:2b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 11.7, raw: "" },
      "qwen3-vl:2b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 4.0, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:8b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 18.2, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:4b (112px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 17.8, raw: "{\"goal\": false, \"team\": null}" },
      "moondream:1.8b (224px, 1 frame, direct prompt)": { pred: "goal", team: "Dark sportswear", goal_correct: true, team_correct: true, latency: 2.0, raw: "The image shows a group of people playing soccer..." },
      "moondream:1.8b (224px, 1 frame, descriptive prompt)": { pred: "goal", team: "Dark sportswear", goal_correct: true, team_correct: true, latency: 3.5, raw: "In the image, there are several people playing soccer on an artificial turf..." },
    },
    "goal_05_606s_Dark-suits": {
      "smolvlm2-2.2b (224px, 3 frames, orig prompt)": { pred: "goal", team: "Team A", goal_correct: true, team_correct: false, latency: 0, raw: "{\"goal\": true, \"team\": \"Team A\"}..." },
      "smolvlm2-2.2b (224px, 3 frames, new prompt)": { pred: "goal", team: "Dark suits", goal_correct: true, team_correct: true, latency: 0.9, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (224px, 3 frames)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 14.3, raw: "" },
      "smolvlm2-2.2b (56px, 23 frames, 2fps)": { pred: "goal", team: "Dark suits", goal_correct: true, team_correct: true, latency: 0.7, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 29.5, raw: "" },
      "qwen3-vl:2b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 7.6, raw: "" },
      "qwen3-vl:2b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 10.5, raw: "" },
      "qwen3-vl:8b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 9.7, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:4b (112px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 21.3, raw: "" },
      "moondream:1.8b (224px, 1 frame, direct prompt)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 1.0, raw: "" },
      "moondream:1.8b (224px, 1 frame, descriptive prompt)": { pred: "goal", team: "Dark sportswear", goal_correct: true, team_correct: false, latency: 2.6, raw: "In the image, there are several people playing soccer on an artificial turf..." },
    },
    "goal_09_947s_Dark-suits": {
      "smolvlm2-2.2b (224px, 3 frames, orig prompt)": { pred: "goal", team: "Team A", goal_correct: true, team_correct: false, latency: 0, raw: "{\"goal\": true, \"team\": \"Team A\"}..." },
      "smolvlm2-2.2b (224px, 3 frames, new prompt)": { pred: "goal", team: "Dark suits", goal_correct: true, team_correct: true, latency: 0.9, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (224px, 3 frames)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 6.4, raw: "" },
      "smolvlm2-2.2b (56px, 23 frames, 2fps)": { pred: "goal", team: "Dark suits", goal_correct: true, team_correct: true, latency: 0.7, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 30.6, raw: "" },
      "qwen3-vl:2b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 7.6, raw: "" },
      "qwen3-vl:2b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 10.4, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:8b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 13.5, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:4b (112px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 21.9, raw: "" },
      "moondream:1.8b (224px, 1 frame, direct prompt)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 1.0, raw: "" },
      "moondream:1.8b (224px, 1 frame, descriptive prompt)": { pred: "goal", team: "Dark sportswear", goal_correct: true, team_correct: false, latency: 2.8, raw: "In the image, there are several people playing soccer on an artificial turf..." },
    },
    "goal_13_1646s_Dark-suits": {
      "smolvlm2-2.2b (224px, 3 frames, orig prompt)": { pred: "goal", team: "Team A", goal_correct: true, team_correct: false, latency: 0, raw: "{\"goal\": true, \"team\": \"Team A\"}..." },
      "smolvlm2-2.2b (224px, 3 frames, new prompt)": { pred: "goal", team: "Dark sportswear", goal_correct: true, team_correct: false, latency: 0.9, raw: "{\"goal\": true, \"team\": \"Dark sportswear\"}..." },
      "qwen3-vl:8b (224px, 3 frames)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 6.5, raw: "" },
      "smolvlm2-2.2b (56px, 23 frames, 2fps)": { pred: "goal", team: "Dark sportswear", goal_correct: true, team_correct: false, latency: 0.7, raw: "{\"goal\": true, \"team\": \"Dark sportswear\"}..." },
      "qwen3-vl:8b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 30.9, raw: "" },
      "qwen3-vl:2b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 7.6, raw: "" },
      "qwen3-vl:2b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 10.4, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:8b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 13.5, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:4b (112px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 17.4, raw: "{\"goal\": false, \"team\": null}" },
      "moondream:1.8b (224px, 1 frame, direct prompt)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 1.0, raw: "" },
      "moondream:1.8b (224px, 1 frame, descriptive prompt)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 2.8, raw: "" },
    },
    "goal_17_2129s_Dark-sportswear": {
      "smolvlm2-2.2b (224px, 3 frames, orig prompt)": { pred: "goal", team: "Team A", goal_correct: true, team_correct: false, latency: 0, raw: "{\"goal\": true, \"team\": \"Team A\"}..." },
      "smolvlm2-2.2b (224px, 3 frames, new prompt)": { pred: "goal", team: "Dark suits", goal_correct: true, team_correct: false, latency: 0.9, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (224px, 3 frames)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 6.5, raw: "" },
      "smolvlm2-2.2b (56px, 23 frames, 2fps)": { pred: "goal", team: "Dark suits", goal_correct: true, team_correct: false, latency: 0.7, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 30.9, raw: "" },
      "qwen3-vl:2b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 7.6, raw: "" },
      "qwen3-vl:2b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 10.4, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:8b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 13.5, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:4b (112px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 22.0, raw: "" },
      "moondream:1.8b (224px, 1 frame, direct prompt)": { pred: "not_goal", team: null, goal_correct: false, team_correct: false, latency: 1.0, raw: "" },
      "moondream:1.8b (224px, 1 frame, descriptive prompt)": { pred: "goal", team: "Dark sportswear", goal_correct: true, team_correct: true, latency: 2.8, raw: "In the image, there are several people playing soccer on an artificial turf..." },
    },
    "nongoal_04_189s": {
      "smolvlm2-2.2b (224px, 3 frames, orig prompt)": { pred: "goal", team: "Team A", goal_correct: false, team_correct: false, latency: 0, raw: "{\"goal\": true, \"team\": \"Team A\"}..." },
      "smolvlm2-2.2b (224px, 3 frames, new prompt)": { pred: "goal", team: "Dark suits", goal_correct: false, team_correct: false, latency: 0.9, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (224px, 3 frames)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 6.5, raw: "" },
      "smolvlm2-2.2b (56px, 23 frames, 2fps)": { pred: "goal", team: "Dark suits", goal_correct: false, team_correct: false, latency: 0.7, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 30.9, raw: "" },
      "qwen3-vl:2b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 7.6, raw: "" },
      "qwen3-vl:2b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 10.4, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:8b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 13.5, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:4b (112px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 13.5, raw: "{\"goal\": false, \"team\": null}" },
      "moondream:1.8b (224px, 1 frame, direct prompt)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 1.0, raw: "" },
      "moondream:1.8b (224px, 1 frame, descriptive prompt)": { pred: "goal", team: "Dark sportswear", goal_correct: false, team_correct: false, latency: 2.7, raw: "In the image, there are several people playing a game of soccer on an outdoor field..." },
    },
    "nongoal_08_1198s": {
      "smolvlm2-2.2b (224px, 3 frames, orig prompt)": { pred: "goal", team: "Team A", goal_correct: false, team_correct: false, latency: 0, raw: "{\"goal\": true, \"team\": \"Team A\"}..." },
      "smolvlm2-2.2b (224px, 3 frames, new prompt)": { pred: "goal", team: "Dark suits", goal_correct: false, team_correct: false, latency: 0.9, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (224px, 3 frames)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 6.5, raw: "" },
      "smolvlm2-2.2b (56px, 23 frames, 2fps)": { pred: "goal", team: "Dark suits", goal_correct: false, team_correct: false, latency: 0.7, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 30.9, raw: "" },
      "qwen3-vl:2b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 7.6, raw: "" },
      "qwen3-vl:2b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 10.4, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:8b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 13.5, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:4b (112px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 23.3, raw: "" },
      "moondream:1.8b (224px, 1 frame, direct prompt)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 1.0, raw: "" },
      "moondream:1.8b (224px, 1 frame, descriptive prompt)": { pred: "goal", team: "Dark sportswear", goal_correct: false, team_correct: false, latency: 2.7, raw: "" },
    },
    "nongoal_12_1557s": {
      "smolvlm2-2.2b (224px, 3 frames, orig prompt)": { pred: "goal", team: "Team A", goal_correct: false, team_correct: false, latency: 0, raw: "{\"goal\": true, \"team\": \"Team A\"}..." },
      "smolvlm2-2.2b (224px, 3 frames, new prompt)": { pred: "goal", team: "Dark suits", goal_correct: false, team_correct: false, latency: 0.9, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (224px, 3 frames)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 6.5, raw: "" },
      "smolvlm2-2.2b (56px, 23 frames, 2fps)": { pred: "goal", team: "Dark suits", goal_correct: false, team_correct: false, latency: 0.7, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 30.9, raw: "" },
      "qwen3-vl:2b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 7.6, raw: "" },
      "qwen3-vl:2b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 10.4, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:8b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 13.5, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:4b (112px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 22.9, raw: "" },
      "moondream:1.8b (224px, 1 frame, direct prompt)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 1.0, raw: "" },
      "moondream:1.8b (224px, 1 frame, descriptive prompt)": { pred: "goal", team: "Dark sportswear", goal_correct: false, team_correct: false, latency: 2.8, raw: "" },
    },
    "nongoal_16_1986s": {
      "smolvlm2-2.2b (224px, 3 frames, orig prompt)": { pred: "goal", team: "Team A", goal_correct: false, team_correct: false, latency: 0, raw: "{\"goal\": true, \"team\": \"Team A\"}..." },
      "smolvlm2-2.2b (224px, 3 frames, new prompt)": { pred: "goal", team: "Dark suits", goal_correct: false, team_correct: false, latency: 0.9, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (224px, 3 frames)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 6.5, raw: "" },
      "smolvlm2-2.2b (56px, 23 frames, 2fps)": { pred: "goal", team: "Dark suits", goal_correct: false, team_correct: false, latency: 0.7, raw: "{\"goal\": true, \"team\": \"Dark suits\"}..." },
      "qwen3-vl:8b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 30.9, raw: "" },
      "qwen3-vl:2b (56px, 23 frames, 2fps)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 7.6, raw: "" },
      "qwen3-vl:2b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 10.4, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:8b (56px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 13.5, raw: "{\"goal\": false, \"team\": null}" },
      "qwen3-vl:4b (112px, 1 frame, num_predict=500)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 23.5, raw: "" },
      "moondream:1.8b (224px, 1 frame, direct prompt)": { pred: "not_goal", team: null, goal_correct: true, team_correct: false, latency: 1.9, raw: "The image shows a group of people playing soccer on an artificial turf field..." },
      "moondream:1.8b (224px, 1 frame, descriptive prompt)": { pred: "goal", team: "Dark sportswear", goal_correct: false, team_correct: false, latency: 2.5, raw: "In the image, there are several people playing a game of soccer on an artificial turf field..." },
    },
  },
};

const ensembleResults = {
  strategies: {
    "or": { f1: 0.714, precision: 0.556, recall: 1.0, accuracy: 0.556, team_accuracy: 0.80, tp: 5, fn: 0, fp: 4, tn: 0, description: "Union: If either model says goal, it's a goal. Best team accuracy improvement." },
    "and": { f1: 0.333, precision: 1.0, recall: 0.20, accuracy: 0.556, team_accuracy: 1.0, tp: 1, fn: 4, fp: 0, tn: 4, description: "Intersection: Only if both models agree on goal. 100% precision but only 20% recall." },
    "cascade": { f1: 0.333, precision: 1.0, recall: 0.20, accuracy: 0.556, team_accuracy: 1.0, tp: 1, fn: 4, fp: 0, tn: 4, description: "Cascade: smolvlm2 first, moondream confirms. Same as AND in this case." },
    "smolvlm2": { f1: 0.714, precision: 0.556, recall: 1.0, accuracy: 0.556, team_accuracy: 0.60, tp: 5, fn: 0, fp: 4, tn: 0, description: "Baseline: smolvlm2-2.2b alone. Always predicts goal." },
    "moondream": { f1: 0.333, precision: 1.0, recall: 0.20, accuracy: 0.556, team_accuracy: 1.0, tp: 1, fn: 4, fp: 0, tn: 4, description: "Baseline: moondream:1.8b direct prompt. Only detects when very sure." },
  },
  best_strategy: "or",
  rationale: "smolvlm2 already has 100% recall (catches all goals), so OR/Union doesn't hurt recall but improves team accuracy from 60% to 80% by using moondream's team identification when it detects."
};

// Predefined demo data for the live clip analysis
const demoData = {
  "goal_01_283s_Dark-sportswear": {
    truth: "goal", truth_team: "Dark sportswear",
    smolvlm2: { pred: "goal", team: "Dark suits", latency: 1.0, raw: "{\"goal\": true, \"team\": \"Dark suits\"}" },
    moondream: { pred: "goal", team: "Dark sportswear", latency: 1.3, raw: "The image shows a group of people playing soccer... a goal was scored by Dark sportswear" }
  },
  "goal_05_606s_Dark-suits": {
    truth: "goal", truth_team: "Dark suits",
    smolvlm2: { pred: "goal", team: "Dark suits", latency: 0.7, raw: "{\"goal\": true, \"team\": \"Dark suits\"}" },
    moondream: { pred: "not_goal", team: null, latency: 1.0, raw: "" }
  },
  "nongoal_04_189s": {
    truth: "not_goal", truth_team: null,
    smolvlm2: { pred: "goal", team: "Dark sportswear", latency: 0.8, raw: "{\"goal\": true, \"team\": \"Dark sportswear\"}" },
    moondream: { pred: "not_goal", team: null, latency: 1.2, raw: "The image shows a group of people playing soccer on an artificial turf field..." }
  }
};
